In [2]:
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)


In [2]:
pip install numpy==1.27.0


Note: you may need to restart the kernel to use updated packages.


ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement numpy==1.27.0 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23

In [3]:
pip install --force-reinstall scipy


  You can safely remove it manually.
  You can safely remove it manually.
  You can safely remove it manually.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.1.3 which is incompatible.
tensorflow-intel 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.1.3 which is incompatible.
thinc 8.3.2 requires numpy<2.1.0,>=2.0.0; python_version >= "3.9", but you have numpy 2.1.3 which is incompatible.

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     --------------------------------- ------ 51.2/60.8 kB 1.3 MB/s eta 0:00:01
     ---------------------------------------- 60.8/60.8 kB 1.1 MB/s eta 0:00:00
  Using cached numpy-2.1.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
   ---------------------------------------- 0.0/44.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/44.8 MB 660.6 kB/s eta 0:01:08
   ---------------------------------------- 0.1/44.8 MB 975.2 kB/s eta 0:00:46
   ---------------------------------------- 0.1/44.8 MB 1.0 MB/s eta 0:00:44
   ---------------------------------------- 0.2/44.8 MB 1.1 MB/s eta 0:00:43
   ---------------------------------------- 0.2/44.8 MB 981.9 kB/s eta 0:00:46
   ---------------------------------------- 0.3/44.8 MB 983.0 kB/s eta 0:00:46
   ---------------------------------------- 0.3/44.8 MB 999.9 kB/s eta 0:00:45
   ---------------------------------------- 0.3/44.8 MB 952.6 kB/s eta 0:00:47

In [4]:
pip install --force-reinstall dask


  Using cached dask-2024.10.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached cloudpickle-3.1.0-py3-none-any.whl.metadata (7.0 kB)
  Using cached partd-1.4.2-py3-none-any.whl.metadata (4.6 kB)
  Using cached toolz-1.0.0-py3-none-any.whl.metadata (5.1 kB)
  Using cached importlib_metadata-8.5.0-py3-none-any.whl.metadata (4.8 kB)
  Using cached zipp-3.20.2-py3-none-any.whl.metadata (3.7 kB)
  Using cached locket-1.0.0-py2.py3-none-any.whl.metadata (2.8 kB)
Using cached dask-2024.10.0-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/97.9 kB ? eta -:--:--
   ------------------------- -------------- 61.4/97.9 kB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 97.9/97.9 kB 1.4 MB/s eta 0:00:00
Using cached cloudpickle-3.1.0-py3-none-any.whl (22 kB)
   ---------------------------------------- 0.0/179.6 kB ? eta -:--:--
   --------------- ------------------------ 71.7/179.6 kB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 174.1/179

  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.1.3 which is incompatible.
thinc 8.3.2 requires numpy<2.1.0,>=2.0.0; python_version >= "3.9", but you have numpy 2.1.3 which is incompatible.

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import dask.dataframe as dd
import numpy as np
import pickle
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from scipy.stats import randint, uniform
from dask_ml.model_selection import train_test_split as dask_train_test_split

# Load large dataset using Dask
df = dd.read_csv(r"C:\Projects\Microsoft-project\Final_Train_DS.csv")

# Check if the dataset contains missing values
missing_values = df.isnull().sum().compute()  # Compute the missing values count
if missing_values.any():
    print("Warning: Dataset contains missing values. Consider handling them before proceeding.")

# Separate features and target variable
X = df.drop('IncidentGrade', axis=1)
y = df['IncidentGrade']

# Split data into training and test sets (use Dask for memory efficiency)
X_train, X_test, y_train, y_test = dask_train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)

# Convert Dask DataFrames to smaller sample NumPy arrays for hyperparameter tuning
X_train_sample = X_train.sample(frac=0.1, random_state=42).compute().reset_index(drop=True)
y_train_sample = y_train.sample(frac=0.1, random_state=42).compute().reset_index(drop=True)

# Standardize features for sample data
scaler = StandardScaler()
X_train_sample_scaled = scaler.fit_transform(X_train_sample)

# Models and parameter grids
models = {
    "Logistic Regression (SGD)": (SGDClassifier(loss='log_loss', max_iter=1000, random_state=42),
                                  {'alpha': uniform(0.0001, 0.01)}),

    "Decision Tree": (DecisionTreeClassifier(random_state=42),
                      {'max_depth': [5, 10, 20, None], 'min_samples_split': randint(2, 20),
                       'min_samples_leaf': randint(1, 20), 'criterion': ['gini', 'entropy']}),

    "Random Forest": (RandomForestClassifier(random_state=42, n_jobs=-1),
                      {'n_estimators': [50, 100], 'max_depth': [10, 20, None],
                       'min_samples_split': randint(2, 20), 'min_samples_leaf': randint(1, 20)}),

    "HistGradientBoosting": (HistGradientBoostingClassifier(random_state=42, max_iter=100),
                             {'learning_rate': uniform(0.01, 0.1), 'max_depth': [3, 6, None]}),

    "XGBoost": (XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42, tree_method='hist'),
                {'n_estimators': [50, 100], 'max_depth': [3, 6], 'learning_rate': uniform(0.01, 0.1)})
}

# Dictionary to store best models and scores
best_models = {}
best_score = 0
best_model_name = None

# Hyperparameter tuning with RandomizedSearchCV on sampled data
for model_name, (model, param_grid) in models.items():
    print(f"\nTuning hyperparameters for {model_name}...")

    random_search = RandomizedSearchCV(model, param_distributions=param_grid, n_iter=10, scoring='accuracy', cv=3,
                                       random_state=42, n_jobs=-1, verbose=1)
    random_search.fit(X_train_sample_scaled, y_train_sample)
    
    # Save the best model from RandomizedSearchCV
    best_models[model_name] = random_search.best_estimator_
    print(f"Best Parameters for {model_name}: {random_search.best_params_}")

    # Fit best model on the full dataset if it supports incremental learning
    if model_name == "Logistic Regression (SGD)":
        # SGDClassifier: Train incrementally on chunks of data
        X_train_computed = X_train.compute()  # Ensure the Dask DataFrame is computed to a NumPy array
        y_train_computed = y_train.compute()  # Ensure the Dask Series is computed to a NumPy array
        for X_batch, y_batch in zip(np.array_split(X_train_computed, 10), np.array_split(y_train_computed, 10)):
            X_batch_scaled = scaler.transform(X_batch)
            best_models[model_name].partial_fit(X_batch_scaled, y_batch, classes=np.unique(y_train_sample))
    else:
        # Train the model on full training data
        X_train_scaled = scaler.transform(X_train.compute())
        best_models[model_name].fit(X_train_scaled, y_train.compute())

    # Predict and evaluate on test data
    X_test_scaled = scaler.transform(X_test.compute())
    y_pred = best_models[model_name].predict(X_test_scaled)

    # Display classification report and confusion matrix
    print(f"\nClassification Report for {model_name}:")
    print(classification_report(y_test.compute(), y_pred))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test.compute(), y_pred))

    # Update the best model based on test score
    test_score = random_search.best_score_
    if test_score > best_score:
        best_score = test_score
        best_model_name = model_name

# Save the best model to a .pkl file
best_model = best_models[best_model_name]
print(f"\nBest Model: {best_model_name} with accuracy: {best_score:.4f}")
with open("best_model.pkl", "wb") as f:
    pickle.dump(best_model, f)
print("Best model saved as 'best_model.pkl'")



Tuning hyperparameters for Logistic Regression (SGD)...
Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best Parameters for Logistic Regression (SGD): {'alpha': np.float64(0.0016599452033620266)}


c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'Series.swapaxes' is deprecated and will be removed in a future version. Please use 'Series.transpose' instead.
  return bound(*args, **kwds)



Classification Report for Logistic Regression (SGD):
              precision    recall  f1-score   support

           0       0.59      0.79      0.68    822191
           1       0.60      0.19      0.29    405897
           2       0.65      0.66      0.65    665284
           3       0.70      0.31      0.43     10202

    accuracy                           0.61   1903574
   macro avg       0.63      0.49      0.51   1903574
weighted avg       0.61      0.61      0.58   1903574

Confusion Matrix:
[[647222  32961 141291    717]
 [230862  78782  95686    567]
 [210720  18541 435927     96]
 [  3967   1470   1584   3181]]

Tuning hyperparameters for Decision Tree...
Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best Parameters for Decision Tree: {'criterion': 'gini', 'max_depth': None, 'min_samples_leaf': 3, 'min_samples_split': 6}

Classification Report for Decision Tree:
              precision    recall  f1-score   support

           0       0.99      0.99      0.9

c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:158: UserWarning: [13:50:25] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


Best Parameters for XGBoost: {'learning_rate': np.float64(0.09324426408004217), 'max_depth': 6, 'n_estimators': 100}


c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\xgboost\core.py:158: UserWarning: [13:51:39] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)



Classification Report for XGBoost:
              precision    recall  f1-score   support

           0       0.79      0.97      0.87    822191
           1       0.93      0.70      0.80    405897
           2       0.94      0.82      0.87    665284
           3       0.92      0.88      0.90     10202

    accuracy                           0.86   1903574
   macro avg       0.89      0.84      0.86   1903574
weighted avg       0.87      0.86      0.86   1903574

Confusion Matrix:
[[793900  12774  15208    309]
 [100261 285050  20333    253]
 [113393   8890 542809    192]
 [  1070     72     81   8979]]

Best Model: Decision Tree with accuracy: 0.9526
Best model saved as 'best_model.pkl'


In [3]:
import pickle

# Assuming `best_models` dictionary has already been populated with the tuned models
random_forest_model = best_models["Random Forest"]

# Save the Random Forest model to a .pkl file
with open("random_forest_model.pkl", "wb") as f:
    pickle.dump(random_forest_model, f)

print("Random Forest model saved as 'random_forest_model.pkl'")


Random Forest model saved as 'random_forest_model.pkl'


In [ ]:
import pandas as pd

report = {
    'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest','HistGradientBoosting', 'XGBoost'],
    'Accuracy':[0.61,0.95,0.98,0.89,0.86],
    'Macro-F1 Score':[ 0.51, 0.90, 0.98, 0.89,0.86],
    'Precision': [0.63,0.92,0.98,0.91,0.89],
    'Recall': [0.49 ,0.90 ,0.97 ,0.89,0.84]

}

# Convert to DataFrame
df = pd.DataFrame(report)

# Print comparison table
print("Comparison Table:")
print(df.to_string(index=False))

# Find the best model based on Macro-F1 Score
best_model = df.loc[df['Macro-F1 Score'].idxmax()]

# Print the best model
print("\nBest Model Based on Macro-F1 Score:")
print(best_model)


Comparison Table:
               Model  Accuracy  Macro-F1 Score  Precision  Recall
 Logistic Regression      0.61            0.51       0.63    0.49
       Decision Tree      0.99            0.99       0.98    0.99
       Random Forest      0.98            0.98       0.98    0.97
HistGradientBoosting      0.89            0.89       0.91    0.89
             XGBoost      0.86            0.86       0.89    0.84

Best Model Based on Macro-F1 Score:
Model             Decision Tree
Accuracy                   0.99
Macro-F1 Score             0.99
Precision                  0.98
Recall                     0.99
Name: 1, dtype: object


In [8]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from joblib import dump

# Load training data
train_data_path = r"C:\Projects\Microsoft-project\Final_Train_DS.csv"
train_df = pd.read_csv(train_data_path)

# Downcast numerical columns in training data
for col in train_df.columns:
    if train_df[col].dtype == 'float64':
        train_df[col] = pd.to_numeric(train_df[col], downcast='float')
    elif train_df[col].dtype == 'int64':
        train_df[col] = pd.to_numeric(train_df[col], downcast='integer')

# Sample a subset of training data for hyperparameter tuning
train_df_subset = train_df.sample(n=500000, random_state=42)
X_train_subset = train_df_subset.drop('IncidentGrade', axis=1)
y_train_subset = train_df_subset['IncidentGrade']

# Initialize RandomForestClassifier with balanced class weight
rf = RandomForestClassifier(class_weight="balanced", random_state=42)

# Define a limited set of hyperparameters
param_dist = {
    'n_estimators': [100, 200],
    'max_depth': [10,15, 20,25],
    'min_samples_split': [5, 10],
    'min_samples_leaf': [2, 4],
    'max_features': ['sqrt','log2']
}

# Initialize RandomizedSearchCV
random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=30,  # Fewer iterations
    scoring='f1_macro',
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# Fit the model using a subset of data
random_search.fit(X_train_subset, y_train_subset)

# Retrieve the best model
best_rf = random_search.best_estimator_
print("Best Hyperparameters:", random_search.best_params_)

# Save the optimized model
model_save_path = r"C:\Projects\Microsoft-project\optimized_random_forest_model.pkl"
dump(best_rf, model_save_path)

# Load and preprocess test data
test_data_path = r"C:\Projects\Microsoft-project\Final_Test_DS.csv"
test_df = pd.read_csv(test_data_path)
X_test = test_df.drop(['IncidentGrade', 'Usage'], axis=1)  
y_test = test_df['IncidentGrade']

# Predict on test set and evaluate
y_test_pred = best_rf.predict(X_test)
print("\nClassification Report on Test Data:")
print(classification_report(y_test, y_test_pred))
print("\nConfusion Matrix on Test Data:")
print(confusion_matrix(y_test, y_test_pred))


Fitting 5 folds for each of 30 candidates, totalling 150 fits


c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\ma\core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


Best Hyperparameters: {'n_estimators': 200, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 25}

Classification Report on Test Data:


c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capita

              precision    recall  f1-score   support

           0       0.86      0.93      0.89   1752940
           1       0.84      0.82      0.83    902698
           2       0.94      0.86      0.90   1492354
           3       0.00      0.00      0.00         0

    accuracy                           0.88   4147992
   macro avg       0.66      0.65      0.65   4147992
weighted avg       0.88      0.88      0.88   4147992


Confusion Matrix on Test Data:
[[1624035   86829   40203    1873]
 [ 115857  737620   48063    1158]
 [ 158034   49267 1284151     902]
 [      0       0       0       0]]


In [5]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
from joblib import dump
from imblearn.over_sampling import SMOTE

# Load and preprocess training data
train_data_path = r"C:\Projects\Microsoft-project\Final_Train_DS.csv"
train_df = pd.read_csv(train_data_path)

# Downcast numerical columns in training data
for col in train_df.columns:
    if train_df[col].dtype == 'float64':
        train_df[col] = pd.to_numeric(train_df[col], downcast='float')
    elif train_df[col].dtype == 'int64':
        train_df[col] = pd.to_numeric(train_df[col], downcast='integer')

# Sample a smaller subset of training data for hyperparameter tuning
train_df_subset = train_df.sample(n=100000, random_state=42)  # Reduced sample size for SMOTE and tuning
X_train_subset = train_df_subset.drop('IncidentGrade', axis=1)
y_train_subset = train_df_subset['IncidentGrade']

# Handle class imbalance using SMOTE with parallel processing
smote = SMOTE(random_state=42, n_jobs=-1)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_subset, y_train_subset)

# Initialize RandomForestClassifier with balanced class weight and warm start
rf = RandomForestClassifier(class_weight="balanced", random_state=42, warm_start=True)

# Define a narrower set of hyperparameters for faster tuning
param_dist = {
    'n_estimators': [100, 150],       # Limited options to speed up tuning
    'max_depth': [10, 15],
    'min_samples_split': [5, 10],
    'min_samples_leaf': [2, 4],
    'max_features': ['sqrt', 'log2']
}

# Initialize RandomizedSearchCV with optimized settings
random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=20,                        # Reduced iterations
    scoring='f1_macro',
    cv=5,                             # Fewer cross-validation folds
    verbose=1,                        # Lower verbosity
    random_state=42,
    n_jobs=-1
)

# Fit the model using the resampled data
random_search.fit(X_train_resampled, y_train_resampled)

# Retrieve the best model
best_rf = random_search.best_estimator_
print("Best Hyperparameters:", random_search.best_params_)

# Save the optimized model
model_save_path = r"C:\Projects\Microsoft-project\Adv_random_forest_model.pkl"
dump(best_rf, model_save_path)

# Load and preprocess test data
test_data_path = r"C:\Projects\Microsoft-project\Final_Test_DS.csv"
test_df = pd.read_csv(test_data_path)
X_test = test_df.drop(['IncidentGrade', 'Usage'], axis=1)  
y_test = test_df['IncidentGrade']

# Predict on test set and evaluate
y_test_pred = best_rf.predict(X_test)
# Accuracy Score
accuracy = accuracy_score(y_test, y_test_pred)
print(f"\nAccuracy on Test Data: {accuracy:.4f}")

# Updated classification report and confusion matrix
print("\nClassification Report on Test Data:")
print(classification_report(y_test, y_test_pred, labels=[0, 1, 2], target_names=['Class 0', 'Class 1', 'Class 2'], zero_division=0))

print("\nConfusion Matrix on Test Data:")
print(confusion_matrix(y_test, y_test_pred, labels=[0, 1, 2]))


c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\imblearn\over_sampling\_smote\base.py:370: FutureWarning: The parameter `n_jobs` has been deprecated in 0.10 and will be removed in 0.12. You can pass an nearest neighbors estimator where `n_jobs` is already set instead.
  warnings.warn(


Fitting 5 folds for each of 20 candidates, totalling 100 fits


c:\Users\harsh\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\ensemble\_forest.py:861: UserWarning: class_weight presets "balanced" or "balanced_subsample" are not recommended for warm_start if the fitted data differs from the full dataset. In order to use "balanced" weights, use compute_class_weight ("balanced", classes, y). In place of y you can use a large enough sample of the full training set target to properly estimate the class frequency distributions. Pass the resulting weights as the class_weight parameter.
  warn(


Best Hyperparameters: {'n_estimators': 150, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt', 'max_depth': 15}

Accuracy on Test Data: 0.8084

Classification Report on Test Data:
              precision    recall  f1-score   support

     Class 0       0.78      0.86      0.82   1752940
     Class 1       0.73      0.76      0.75    902698
     Class 2       0.94      0.77      0.85   1492354

   micro avg       0.82      0.81      0.81   4147992
   macro avg       0.82      0.80      0.80   4147992
weighted avg       0.83      0.81      0.81   4147992


Confusion Matrix on Test Data:
[[1515014  171680   45954]
 [ 171629  689309   29466]
 [ 249877   85926 1148899]]
